# This is a basic workflow to help you get started with Actions

name: AutoBuild

# Controls when the workflow will run
on:

  watch:
    types: [started]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Fetch latest wsl kernel source
        run: git clone https://github.com/microsoft/WSL2-Linux-Kernel -b linux-msft-wsl-5.10.y
        
      - name: Install build tool chain
        run: sudo apt update && sudo apt install build-essential flex bison libssl-dev libelf-dev -y
      
      - name: Enable drivers for anbox
        run: |
          cd WSL2-Linux-Kernel
          cp Microsoft/config-wsl .config && patch -p1 < ../.config.patch
      
      - name: Build linux kernel
        run: |
          cd WSL2-Linux-Kernel
          make
        
      - uses:  actions/upload-artifact@v2
        with:
          name: kernel
          path: WSL2-Linux-Kernelarch/x86/boot/bzImage
